Repository np-guard/cloud-resource-collector, pull requests merged in 2023-11, with the labels that each got.

#133 collect transit connections
  go.mod
  go.sum
  pkg/ibm/datamodel/data_model.go
  pkg/ibm/datamodel/resources_container_model.go
  pkg/ibm/datamodel/test/data/demo-with-instances-config.json
  pkg/ibm/datamodel/test/data/iks-on-goldeneye-vpc-config.json
  pkg/ibm/datamodel/test/data/transit-gateways.json
  pkg/ibm/datamodel/test/unmarshal_test.go
  pkg/ibm/resources_container.go
  pkg/ibm/vpc_collection.go
Labels: size/XXL

#137 A cli arg to define cloud regions to collect from
  README.md
  cmd/collect/main.go
  cmd/collect/parse_args.go
  pkg/aws/resources_container.go
  pkg/common/resources_container_inf.go
  pkg/ibm/regions.go
  pkg/ibm/resources_container.go
Labels: size/L

#139 Add copyright header
  cmd/collect/main.go
  cmd/collect/output_resources.go
  cmd/collect/parse_args.go
  pkg/aws/resources_container.go
  pkg/common/resources_container_inf.go
  pkg/ibm/datamodel/data_model.go
  pkg/ibm/datamodel/resources_container_model.go
  pkg/ibm/datamodel/test/unmarshal_test.go
  pkg/ibm/iks_collection.go
  pkg/ibm/regions.go
  pkg/ibm/resources_container.go
  pkg/ibm/vpc_collection.go
Labels: size/M

#142 write to log progress messages
  pkg/ibm/resources_container.go
Labels: size/XS
