Repository np-guard/cloud-resource-collector, pull requests merged in 2024-06, with the labels that each got.

#263 Upgrade packages
  go.mod
  go.sum
Labels: size/M

#265 add provider field to json config output
  cmd/collect/parse_args.go
  pkg/aws/resources_container.go
  pkg/common/resources_container_inf.go
  pkg/factory/factory.go
  pkg/ibm/datamodel/resources_container_model.go
  pkg/ibm/datamodel/test/data/demo-with-instances-config.json
  pkg/ibm/datamodel/test/data/experiments_env.json
  pkg/ibm/datamodel/test/data/iks-on-goldeneye-vpc-config.json
  pkg/ibm/datamodel/test/data/transit-gateways.json
Labels: size/M

#270 Bump github.com/IBM/vpc-go-sdk from 0.51.0 to 0.52.0
  go.mod
  go.sum
  pkg/ibm/datamodel/test/data/demo-with-instances-config.json
  pkg/ibm/datamodel/test/data/experiments_env.json
  pkg/ibm/datamodel/test/data/transit-gateways.json
Labels: size/L

#272 version v0.11.0
  pkg/version/version.go
Labels: size/XS

#277 add aws unmarshal test
  pkg/aws/test/data/aws_example.json
  pkg/aws/test/unmarshal_test.go
Labels: size/L

#283 Bump github.com/IBM/networking-go-sdk from 0.46.1 to 0.47.1
  go.mod
  go.sum
  pkg/ibm/datamodel/test/data/transit-gateways.json
Labels: size/S

#282 Using Cobra for defining CLI commands and flags
  Makefile
  README.md
  cmd/collect/collect_resources.go
  cmd/collect/main.go
  cmd/collect/parse_args.go
  cmd/collect/subcmds.go
  go.mod
  go.sum
  pkg/aws/resources_container.go
  pkg/common/provider.go
  pkg/common/resources_container_inf.go
  pkg/factory/factory.go
  pkg/ibm/datamodel/resources_container_model.go
Labels: size/L

#284 version v0.12.0
  pkg/version/version.go
Labels: size/XS
