Repository np-guard/cloud-resource-collector, pull requests merged in 2024-02, with the labels that each got.

#192 Adding more linters
  .golangci.yml
Labels: size/M

#196 get resource group by name
  README.md
  cmd/collect/parse_args.go
  pkg/ibm/resources_container.go
Labels: size/M

#197 fix tests issues for PR Bump github.com/IBM/vpc-go-sdk from 0.47.0 to 0.48.0
  go.mod
  go.sum
  pkg/ibm/datamodel/test/data/demo-with-instances-config.json
  pkg/ibm/datamodel/test/data/experiments_env.json
  pkg/ibm/datamodel/test/data/transit-gateways.json
Labels: size/L

#198 Extend ResourceContainer API with GetResources() method
  cmd/collect/main.go
  cmd/collect/parse_args.go
  pkg/aws/resources_container.go
  pkg/common/resources_container_inf.go
  pkg/factory/factory.go
  pkg/ibm/resources_container.go
Labels: size/M

#201 version v0.5.2
  pkg/version/version.go
Labels: size/XS

#204 Run golangci-lint action according to docs
  .github/workflows/golangci-lint.yml
Labels: size/XS
